### ISSUE TITLE
RuntimeError: communication with device failed

### ISSUE THREAD

**Issue by sperez91** [llvllch/stonks#5]
I'm trying to get it to work on this 7.8 in screen: https://www.waveshare.com/wiki/7.8inch_e-Paper_HAT
Their demo execution works.

But when I try to run the cryptotick.py I get the error "communication with device failed". See screenshot. Any help will be appreciated.
![2021-09-24 21_45_41-Window](https://user-images.githubusercontent.com/5923672/134758472-25ad0eaa-e56d-42c6-8544-5d46a8548f4d.png)
I

**Comment by llvllch** [comment]
Ah..That can happen if a previous bit of code still has a hold of the display. A good old reboot before running again usually does the trick

**Comment by sperez91** [comment]
Thank you! The reboot didn't work because the drawing stayed on the screen. But I ran the demo exec until it clears the screen and then tried the cryptotick.py again and now it works! See screenshot.
![2021-09-25 10_52_20-Window](https://user-images.githubusercontent.com/5923672/134781446-5ac0e4e9-e176-4ffb-aa64-a4beb4369520.png)

Is there a command I can use to clear the screen more easily?
How can I stretch it to use the entire screen?

All the help is much appreciated. Thank you so much!

**Comment by llvllch** [comment]
Looking good! 

If I was starting again, I would have anticipated people using other screens and did a better job for scaling. Got to love hindsight.

That said, it shouldn't be too hard to change. When scaling between the 6 inch screen and yours, you will have a horizontal scaling factor and a vertical one. 
Horizontal Resolution of 7.8/ Horizontal resolution of 6, 1872/1448 = **1.29** and 
Vertical Resolution of 7.8/ Vertical resolution of 6,1404/1072 = **1.31**.

I would just say both scaling factors are **1.3** and just go through the code and add that multiplier to all coordinates/ image sizes. Give it a try and come back if you get stuck :)

I'll close this issue, but feel free to submit again as you hit bumps in the road. 

Good luck!
