### ISSUE TITLE
Resizing elements for 7.8in screen

### ISSUE THREAD

**Issue by sperez91** [llvllch/stonks#6]
I've been resizing everything in your script for the [7.8in Waveshare screen](https://www.waveshare.com/wiki/7.8inch_e-Paper_HAT) to a factor of 1.3 and changed screen size from **1448, 1072** to **1872, 1404**

Please take a look at the screenshot. I'm still learning Python so I hope you could help me with the following:

1. How do I reduce the margin at the top?
2. The increased sizes made the price and graph become unaligned, how do I prevent that from happening?
3. Which line determines the size of the graphs? I want to make them bigger because there's still a lot of white space on the right side.

![2021-10-05 18_31_31-Photo - Google Photos](https://user-images.githubusercontent.com/5923672/136126652-9bcb358a-1a68-44e1-a6ed-4332447bdf74.png)

Thank you so much for making this script available to the public.

**Comment by sperez91** [comment]
Hey man, thank you so much. I understand the code a lot better now. I've put it in a frame on my desk, see attached photo.

![2021-10-17 18_06_59-Photo in Cryptoticker - Google Photos](https://user-images.githubusercontent.com/5923672/137652522-ee9cf414-788e-42b0-ab2a-8dab8d62684d.png)

**Comment by Phil228822** [comment]
Thank you for posting on this. Can you tell me where in the script you were able to resize by a factor of 1.3?
