### ISSUE TITLE
Script stops after a few hours

### ISSUE THREAD

**Issue by sperez91** [llvllch/stonks#7]
As you may already know, I've adapted your script for a 7.8in screen. I've noticed that every few hours it stops running without indication of anything crashing or going wrong. Sometimes after 2 hours, sometimes after 24 hours. The terminal just sits there displaying the log of the last run, and the RPi is responsive and functional. Is this something I may have caused with my modifications or have you experienced it before?

![2021-10-18 12_51_38-192 168 1 82 (raspberrypi) - VNC Viewer](https://user-images.githubusercontent.com/5923672/137797555-0a64f805-c129-4c7d-82ad-998d3a29ada1.png)

**Comment by llvllch** [comment]
This doesn't look like it's the code throwing an error. The logging info is a little different on the current version than it is on your version, so without knowing what your code is doing, I can't tell.

Check the logs in /var/log/syslog to see if there are any clues there. Also, see if there are any issues in the repository for the display code.
